name = "simple-a"
license = "MIT"
licenselink = "https://github.com/AlexFinn/simple-a/blob/master/LICENSE.md"
description = "Minimalistic Hugo theme"

tags = ["alexfinn", ]
features = ["blog", ]

[author]
    name = "alexfinn"
    homepage = "http://ru.alexfinn.eu/"
    source_repo = "https://github.com/AlexFinn/simple-a"
